# Generated by Django 5.0 on 2024-01-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("repaint", "Repaint"),
                            ("renumbered", "Renumbered"),
                            ("registration_change", "Registration Change"),
                            ("name_applied", "Name Applied"),
                            ("name_removed", "Name Removed"),
                            ("branding_applied", "Branding Applied"),
                            ("branding_removed", "Branding Removed"),
                            ("garage_transfer", "Garage Transfer"),
                            ("entered_service", "Entered Service"),
                            ("withdrawn", "Withdrawn"),
                            ("reinstated", "Reinstated"),
                            ("preserved", "Preserved"),
                            ("scrapped", "Scrapped"),
                            ("sold", "Sold"),
                            ("delivered", "Delivered"),
                            ("feature_added", "Feature Added"),
                            ("feature_removed", "Feature Removed"),
                            ("vor", "Vehicle Off Road"),
                            ("returned_to_service", "Returned to Service"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("unknown", "Unknown"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                (
                    "is_future_event",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark if this event is planned for the future",
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically generated from vehicle changes",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_history_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_events",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle History Event",
                "verbose_name_plural": "Vehicle History Events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleHistoryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vehicle_history.vehiclehistoryevent",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_attachments",
                        to="photos.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle History Attachment",
                "verbose_name_plural": "Vehicle History Attachments",
            },
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["vehicle"], name="vehicle_h_vehicle_id_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["event_type"], name="vehicle_h_event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["event_date"], name="vehicle_h_event_date_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["is_future_event"], name="vehicle_h_is_future_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["created_at"], name="vehicle_h_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["vehicle", "event_date"], name="vehicle_h_veh_date_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclehistoryevent",
            index=models.Index(fields=["vehicle", "event_type"], name="vehicle_h_veh_type_idx"),
        ),
    ]
