# Generated by Django 6.0.3 on 2026-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_vehicle_7d348c_idx',
            old_name='vehicle_h_vehicle_id_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_event_t_eca55d_idx',
            old_name='vehicle_h_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_event_d_38cba8_idx',
            old_name='vehicle_h_event_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_is_futu_8479ae_idx',
            old_name='vehicle_h_is_future_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_created_8e2cb4_idx',
            old_name='vehicle_h_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_vehicle_ba7661_idx',
            old_name='vehicle_h_veh_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclehistoryevent',
            new_name='vehicle_his_vehicle_79ac8a_idx',
            old_name='vehicle_h_veh_type_idx',
        ),
    ]
