FROM node:20-slim

WORKDIR /app/

COPY package.json package-lock.json /app/
RUN npm ci

COPY frontend /app/frontend
COPY .parcelrc tsconfig.json /app/
RUN npm run build


FROM python:3.13-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    git \
    libpq-dev \
    geos-bin \
    libgeos-dev \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app/

COPY uv.lock pyproject.toml /app/
RUN uv sync --frozen

ENV PATH="/app/.venv/bin:$PATH"
ENV GDAL_LIBRARY_PATH=/usr/lib/gdal/libgdal.so

# Install Playwright
RUN uv pip install playwright
RUN python -m playwright install chromium

COPY --from=0 /app/node_modules/htmx.org/dist /app/node_modules/htmx.org/dist
COPY --from=0 /app/node_modules/reqwest/reqwest.min.js /app/node_modules/reqwest/
COPY --from=0 /app/busstops/static /app/busstops/static
COPY . /app/

ENV PORT=8000 STATIC_ROOT=/staticfiles

EXPOSE 8000
CMD ["gunicorn", "buses.wsgi"]
