services:
  web_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: sh -c "uv sync --group dev --group test; ./manage.py collectstatic --noinput; DEBUG=1 exec ./manage.py runserver 0.0.0.0:8000"
    container_name: bfdev-django
    environment:
      - SECRET_KEY=${SECRET_KEY-}
      - DATABASE_URL=${DATABASE_URL-postgis://dev_user:dev_password@bfdev-postgres:5432/betterfleets_dev}
      - REDIS_URL=${REDIS_URL-redis://bfdev-redis:6379}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-localhost 127.0.0.1 dev.eeveeit.uk}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS-http://localhost http://dev.eeveeit.uk https://dev.eeveeit.uk}
      - FIDO2_RP_ID=${FIDO2_RP_ID-localhost}
      - FIDO2_RP_NAME=${FIDO2_RP_NAME-BetterFleet-Dev}
      - FIDO2_RP_ORIGINS=${FIDO2_RP_ORIGINS-http://localhost:18000,http://dev.eeveeit.uk}
      - NTA_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PYTHONWARNINGS=all
    ports:
      - "18000:8000"
    restart: on-failure
    volumes:
      - .:/app:cached
      - media_dev:/app/media
    depends_on:
      - postgres_dev
      - redis_dev

  postgres_dev:
    image: postgis/postgis
    container_name: bfdev-postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - PGUSER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=betterfleets_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_dev:
    image: redis
    container_name: bfdev-redis

volumes:
  postgres_data_dev:
  media_dev:
