# Generated by Django 5.2 on 2026-07-26 13:19

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("busstops", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "favourite_type",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("vehicle", "Vehicle"),
                            ("service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, help_text="Optional notes about this favourite")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favourited_by",
                        to="busstops.operator",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favourited_by",
                        to="busstops.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favourited_by",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "favourite",
                "verbose_name_plural": "favourites",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user", "favourite_type", "operator", "vehicle", "service")},
        ),
    ]
