# Generated by Django 5.2 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0013_stoppoint_description_stoppoint_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="operators"),
        ),
        migrations.AddField(
            model_name="operator",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operator",
            name="manual_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="social_fb",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="social_other",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="social_x",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="slogan",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
