# Generated by Django 6.0.3 on 2026-04-04 18:59

import django.db.models.deletion
from django.db import migrations, models


def add_operator_organisation_if_missing(apps, schema_editor):
    Operator = apps.get_model("busstops", "Operator")
    Organisation = apps.get_model("busstops", "Organisation")
    table_name = Operator._meta.db_table
    existing_columns = {
        column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table_name
        )
    }
    if "organisation_id" in existing_columns:
        return

    field = models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        to=Organisation,
    )
    field.set_attributes_from_name("organisation")
    schema_editor.add_field(Operator, field)


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0019_operator_theme_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorgroup',
            options={'ordering': ('name',)},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_operator_organisation_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='operator',
                    name='organisation',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.organisation'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='homepagenotice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operatorgroupdepot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
