# Generated by Django 6.0.3 on 2026-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0023_operator_preserved_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='accurate_as_of',
            field=models.DateField(blank=True, help_text="The date this operator's fleet information is accurate as of.", null=True),
        ),
    ]
