# Generated by Django 6.0.3 on 2026-05-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0032_svg_logo_support'),
        ('busstops', '0035_blog_posts_and_operator_vehicle_columns'),
    ]

    operations = [
    ]
