# Generated by Django 6.0.3 on 2026-05-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0036_merge_0032_svg_logo_support_0035_merge_20260505_2307'),
        ('busstops', '0053_merge_0037_0052'),
    ]

    operations = [
    ]
