# Generated by Django 6.0.3 on 2026-05-28 22:59

import busstops.fields
import busstops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0054_merge_20260528_2358'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bustimessyncstate',
            new_name='busstops_bu_object__fff346_idx',
            old_name='busstops_bu_object__7259f3_idx',
        ),
        migrations.RenameIndex(
            model_name='bustimessyncstate',
            new_name='busstops_bu_local_m_f68797_idx',
            old_name='busstops_bu_local_m_90aab3_idx',
        ),
        migrations.RenameIndex(
            model_name='datachangelog',
            new_name='busstops_da_status_328738_idx',
            old_name='busstops_da_status_8f8229_idx',
        ),
        migrations.RenameIndex(
            model_name='datachangelog',
            new_name='busstops_da_source_b58cb5_idx',
            old_name='busstops_da_source_3b9f8a_idx',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='routenotice',
            name='other_services',
            field=models.ManyToManyField(blank=True, related_name='related_route_notices', to='busstops.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_rail_replacement',
            field=models.BooleanField(db_index=True, default=False, help_text='This service is a rail replacement service.'),
        ),
        migrations.AddField(
            model_name='service',
            name='train_operator',
            field=models.CharField(blank=True, help_text='The train operator this service is covering for.', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manufacturersite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=busstops.models.operator_slug_source, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorvehiclecolumn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=busstops.models.service_slug_source, unique=True),
        ),
    ]
