# Generated by Django 6.0.3 on 2026-06-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0047_preservationgroup_verbose_names'),
        ('busstops', '0056_operator_check_dvla'),
    ]

    operations = [
    ]
