# Generated by Django 6.0.3 on 2026-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0059_stoppoint_crs_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_requires_operator_or_preservation_group',
        ),
        migrations.AlterModelOptions(
            name='operatorgroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preservationgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preservationgroup',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='operator',
            name='user_role',
            field=models.CharField(blank=True, choices=[('owns', 'owns'), ('runs', 'runs'), ('manages', 'manages'), ('represents', 'represents')], default='', help_text='How this user relates to the operator or group (shown on the public page).', max_length=16),
        ),
        migrations.AlterField(
            model_name='preservationgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
