# Generated by Django 6.0.3 on 2026-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0061_service_school_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
