# Generated by Django 6.0.3 on 2026-07-08 23:38

import busstops.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0062_organisation_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, help_text='Upload an SVG, PNG, JPG, JPEG, or WebP logo up to 256 KB.', null=True, upload_to='government-authorities/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg', 'webp')), busstops.models.validate_logo_file_size])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='government-authorities/banners')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('social_x', models.URLField(blank=True)),
                ('social_fb', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('social_tiktok', models.URLField(blank=True)),
                ('social_threads', models.URLField(blank=True)),
                ('social_bluesky', models.URLField(blank=True)),
                ('social_mastodon', models.URLField(blank=True)),
                ('social_other', models.URLField(blank=True)),
                ('header_background', models.CharField(blank=True, max_length=20)),
                ('header_foreground', models.CharField(blank=True, max_length=20)),
                ('accent_colour', models.CharField(blank=True, max_length=20)),
                ('card_background', models.CharField(blank=True, max_length=20)),
                ('button_background', models.CharField(blank=True, max_length=20)),
                ('button_foreground', models.CharField(blank=True, max_length=20)),
                ('custom_css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'government authority',
                'verbose_name_plural': 'government authorities',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='government_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.governmentauthority'),
        ),
    ]
