# Generated by Django 6.0.3 on 2026-09-02

import re

import busstops.models
from django.db import migrations, models


def copy_service_colours(apps, schema_editor):
    Service = apps.get_model("busstops", "Service")

    for service in Service.objects.select_related("legacy_colour"):
        legacy_colour = service.legacy_colour
        if legacy_colour is None:
            continue

        update_fields = []
        if re.fullmatch(
            r"#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?",
            legacy_colour.background or "",
        ):
            service.colour = legacy_colour.background
            update_fields.append("colour")
        if (
            not service.line_brand
            and legacy_colour.use_name_as_brand
            and legacy_colour.name
            and legacy_colour.name != service.line_name
        ):
            service.line_brand = legacy_colour.name
            update_fields.append("line_brand")
        if update_fields:
            service.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0063_governmentauthority_operator_government_authority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="colour",
            new_name="legacy_colour",
        ),
        migrations.AddField(
            model_name="service",
            name="colour",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hexadecimal colour, e.g. #1d4ed8.",
                max_length=7,
                validators=[busstops.models.validate_hex_colour],
            ),
            preserve_default=False,
        ),
        migrations.RunPython(copy_service_colours, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="service",
            name="legacy_colour",
        ),
    ]
