# Generated by Django 6.0.3 on 2026-05-22 18:34

import disruptions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0010_alter_situation_source_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(default=disruptions.models.get_default_situation_source_pk, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
