# Generated by Django 6.0.3 on 2026-05-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0012_remove_operator_parent"),
        ("fares", "0002_fare_farerule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busstops.operator",
                    ),
                ),
            ],
            options={
                "ordering": ("operator__name", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="TicketAcceptance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busstops.service",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fares.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ("service__line_name", "service__description", "service__id"),
                "unique_together": {("ticket", "service")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="services",
            field=models.ManyToManyField(
                blank=True, through="fares.TicketAcceptance", to="busstops.service"
            ),
        ),
    ]
