# Generated by Django 6.0.3 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0003_ticket_ticketacceptance_ticket_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="adult_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="child_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="days_valid_for",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="zone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
