# Generated by Django 6.0.3 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0004_ticket_zone_ticket_adult_price_ticket_child_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("operator__name", "ticket_type", "name", "id")},
        ),
    ]
