# Generated by Django 6.0.3 on 2026-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registrationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
