# Generated by Django 6.0.3 on 2026-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_discord_widget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
