# Generated by Django 6.0.3 on 2026-05-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profiletag_id'),
        ('accounts', '0008_user_blocked_from_reviews'),
    ]

    operations = [
    ]
