# Generated by Django 6.0.3 on 2026-05-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260510_0020'),
        ('accounts', '0009_user_fleet_logging_public'),
    ]

    operations = [
    ]
