# Generated by Django 6.0.3 on 2026-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='operators',
        ),
        migrations.DeleteModel(
            name='RegistrationSettings',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
