# Generated by Django 6.0.3 on 2026-07-20 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_invitation_operators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletag',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='profile_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='manual_tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_users', to='accounts.profiletag'),
        ),
    ]
