# Generated by Django 6.0.3 on 2026-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profiletag_users_alter_user_manual_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_advanced',
            field=models.BooleanField(default=False, help_text='Enable advanced editing controls'),
        ),
    ]
