# Generated by Django 6.0.3 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_add_view_advanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="advanced_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enable advanced fleet export features",
            ),
        ),
    ]
