# Generated by Django 6.0.3 on 2026-05-22 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_fleetridelog'),
        ('vehicles', '0058_vehiclerevision_edit_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDrivingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this driving experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_driving_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'fleet driving log',
                'verbose_name_plural': 'fleet driving logs',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle'), name='fleet_unique_user_vehicle_driving_log')],
            },
        ),
    ]
