# Generated by Django 6.0.3 on 2026-05-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_fleetdrivinglog'),
        ('vehicles', '0059_alter_vehicle_fleet_support_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVehicleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('headcode', models.CharField(blank=True, max_length=16)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_locations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'live vehicle location',
                'verbose_name_plural': 'live vehicle locations',
                'ordering': ('-created_at',),
            },
        ),
    ]
