# Generated by Django 6.0.3 on 2026-05-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_livevehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevehiclelocation',
            name='lateness',
            field=models.IntegerField(blank=True, help_text='Lateness in minutes (negative for early)', null=True),
        ),
        migrations.AddField(
            model_name='livevehiclelocation',
            name='rotation',
            field=models.IntegerField(blank=True, help_text='Vehicle heading in degrees (0-360)', null=True),
        ),
    ]
