# Generated by Django 6.0.3 on 2026-06-22 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_livevehiclelocation_lateness_and_more'),
        ('vehicles', '0064_previous_operators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPhotoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this photograph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_photo_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'fleet photo log',
                'verbose_name_plural': 'fleet photo logs',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle'), name='fleet_unique_user_vehicle_photo_log')],
            },
        ),
    ]
