# Generated by Django 6.0.3 on 2026-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_fleetphotolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetphotolog',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
