# Generated by Django 6.0.3 on 2026-07-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_pinnedoperator'),
        ('fleet', '0007_fleetphotolog_quantity'),
    ]

    operations = [
    ]
