# Generated by Django 5.2 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bustimes", "0013_route_timezone_alter_timetabledatasource_search"),
        ("busstops", "0014_operator_fleet_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="garage",
            name="region",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="busstops.region"),
        ),
        migrations.AddField(
            model_name="garage",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="garage",
            name="manual_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
