# Generated by Django 6.0.3 on 2026-05-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0016_route_event_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='event_visibility_weeks',
        ),
    ]
