# Generated by Django 6.0.3 on 2026-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0018_routewaypoint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='routewaypoint',
            new_name='bustimes_ro_route_l_ac4f76_idx',
            old_name='bustimes_route_link_order_idx',
        ),
        migrations.AlterField(
            model_name='routewaypoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
