# Generated by Django 6.0.3 on 2026-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0063_governmentauthority_operator_government_authority'),
        ('bustimes', '0019_rename_bustimes_route_link_order_idx_bustimes_ro_route_l_ac4f76_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='operator',
        ),
        migrations.AddField(
            model_name='garage',
            name='operators',
            field=models.ManyToManyField(blank=True, to='busstops.operator'),
        ),
    ]
