# Generated by Django 6.0.3 on 2026-07-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0063_governmentauthority_operator_government_authority'),
        ('bustimes', '0020_remove_garage_operator_garage_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether simulation is enabled for this service')),
                ('vehicle_count', models.PositiveSmallIntegerField(default=1, help_text='Number of vehicles to simulate for this service')),
                ('destination_inbound', models.CharField(blank=True, help_text='Custom destination name for inbound trips', max_length=255)),
                ('destination_outbound', models.CharField(blank=True, help_text='Custom destination name for outbound trips', max_length=255)),
                ('vehicle_config', models.JSONField(blank=True, default=dict, help_text='Vehicle configuration data (IDs, registrations, names)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The service to simulate tracking for', on_delete=django.db.models.deletion.CASCADE, related_name='simulation_configs', to='busstops.service')),
            ],
            options={
                'indexes': [models.Index(fields=['service'], name='bustimes_si_service_106ab4_idx'), models.Index(fields=['enabled'], name='bustimes_si_enabled_9c1180_idx')],
                'unique_together': {('service',)},
            },
        ),
    ]
