# Generated by Django 6.0.3 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bustimes", "0021_simulationconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
