# Generated by Django 6.0.3 on 2026-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_historicallivery_fleet_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallivery',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
