# Generated by Codex on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0023_alter_historicallivery_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="preserved",
            field=models.BooleanField(
                default=False,
                help_text="Keep this vehicle as a preserved record outside the active fleet list.",
            ),
        ),
    ]
