# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0026_operator_fleet_list_notes"),
        ("vehicles", "0024_vehicle_preserved"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFleet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_fleets",
                        to="busstops.operator",
                    ),
                ),
            ],
            options={
                "ordering": ("-year",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalFleetVehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fleet_number", models.PositiveIntegerField(blank=True, null=True)),
                ("fleet_code", models.CharField(blank=True, max_length=24)),
                ("reg", models.CharField(blank=True, max_length=24)),
                ("code", models.CharField(blank=True, max_length=255)),
                ("branding", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("vehicle_type_name", models.CharField(blank=True, max_length=255)),
                ("livery_name", models.CharField(blank=True, max_length=255)),
                ("colours", models.CharField(blank=True, max_length=255)),
                ("garage_name", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="vehicles.historicalfleet",
                    ),
                ),
                (
                    "linked_vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a current vehicle; historical rows are not searchable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ("fleet_number", "fleet_code", "reg", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="historicalfleet",
            constraint=models.UniqueConstraint(
                fields=("operator", "year"),
                name="historicalfleet_operator_year_uniq",
            ),
        ),
    ]
