# Generated by Django 6.0.3 on 2026-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0028_additionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Historical vehicle',
                'verbose_name_plural': 'Historical vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.vehicle',),
        ),
        migrations.AlterField(
            model_name='additionrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='additionrequest',
            name='request_type',
            field=models.CharField(choices=[('livery', 'Liveries'), ('vehicle_type', 'Vehicles'), ('operator', 'Operators'), ('garage', 'Garage'), ('vehicle', 'Vehicles')], max_length=20),
        ),
    ]
