# Generated by Django 6.0.3 on 2026-04-18 23:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0028_routenotice'),
        ('bustimes', '0014_garage_fleet_metadata'),
        ('vehicles', '0029_historicalvehicle_alter_additionrequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='additionrequest',
            name='reviewed_by',
        ),
        migrations.RemoveConstraint(
            model_name='historicalfleet',
            name='historicalfleet_operator_year_uniq',
        ),
        migrations.DeleteModel(
            name='HistoricalVehicle',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='vehicle_operator_and_code_live',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='vehicle_historical_fleet_code_uniq',
        ),
        migrations.RemoveField(
            model_name='historicallivery',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='historicallivery',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='historicallivery',
            name='manual_updated_at',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='manual_updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='manual_updated_at',
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), models.F('operator'), name='vehicle_operator_and_code'),
        ),
        migrations.DeleteModel(
            name='AdditionRequest',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='historical_fleet',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='linked_vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='manual_updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='preserved',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='prev_registration',
        ),
        migrations.DeleteModel(
            name='HistoricalFleet',
        ),
    ]
