# Generated by Django 6.0.3 on 2026-04-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_vehicle_prev_registration'),
        ('vehicles', '0030_remove_additionrequest_requested_by_and_more'),
    ]

    operations = [
    ]
