# Generated by Django 6.0.3 on 2026-05-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0038_alter_vehicletypegroup_id'),
        ('vehicles', '0038_vehicle_historical_fleet_year'),
    ]

    operations = [
    ]
