# Generated by Django 6.0.3 on 2026-05-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0039_livery_description'),
        ('vehicles', '0039_merge_20260504_2221'),
    ]

    operations = [
    ]
