# Generated by Django 6.0.3 on 2026-05-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0040_livery_wiki_fields'),
        ('vehicles', '0040_merge_20260505_1421'),
    ]

    operations = [
    ]
