# Generated by Django 6.0.3 on 2026-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0041_merge_20260505_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallivery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicallivery',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallivery',
            name='model_differences',
            field=models.TextField(blank=True),
        ),
    ]
