# Generated by Django 6.0.3 on 2026-05-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0041_livery_creator'),
        ('vehicles', '0042_historicallivery_description_historicallivery_image_and_more'),
    ]

    operations = [
    ]
