# Generated by Django 6.0.3 on 2026-05-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0042_historicallivery_creator'),
        ('vehicles', '0043_merge_20260505_1459'),
    ]

    operations = [
    ]
