# Generated by Django 6.0.3 on 2026-05-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0043_vehicle_reviews_profile_fields_and_accessibility'),
        ('vehicles', '0044_merge_20260505_1513'),
    ]

    operations = [
    ]
