# Generated by Django 6.0.3 on 2026-05-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0044_alter_vehiclereview_rating'),
        ('vehicles', '0045_merge_20260506_2045'),
    ]

    operations = [
    ]
