# Generated by Django 6.0.3 on 2026-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0046_merge_20260506_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclefeature',
            options={'ordering': ('category', 'name')},
        ),
        migrations.AlterField(
            model_name='vehiclereview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
