# Generated by Django 6.0.3 on 2026-05-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0045_remove_unique_vehicle_review_constraint'),
        ('vehicles', '0047_alter_vehiclefeature_options_alter_vehiclereview_id'),
    ]

    operations = [
    ]
