# Generated by Django 6.0.3 on 2026-05-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0048_merge_20260508_2007'),
        ('vehicles', '0048_review_moderation'),
    ]

    operations = [
    ]
