# Generated by Django 6.0.3 on 2026-05-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0049_merge_0048_merge_20260508_2007_0048_review_moderation'),
        ('vehicles', '0049_vehicle_review_delete_permission'),
    ]

    operations = [
    ]
