# Generated by Django 6.0.3 on 2026-05-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0050_merge_20260510_0020'),
        ('vehicles', '0050_vehiclenamepage'),
    ]

    operations = [
    ]
