# Generated by Django 6.0.3 on 2026-05-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0051_merge_0050_merge_20260510_0020_0050_vehiclenamepage'),
        ('vehicles', '0051_vehiclerevision_garage_fields'),
    ]

    operations = [
    ]
