# Generated by Django 6.0.3 on 2026-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0052_merge_20260511_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclenamepage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
