# Generated by Django 6.0.3 on 2026-05-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0044_vehicle_historical_fleet_creator'),
        ('vehicles', '0053_alter_vehiclenamepage_id'),
    ]

    operations = [
    ]
