# Generated by Django 6.0.3 on 2026-05-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0053_vehicle_dvla_mot_status_and_tax_choices'),
        ('vehicles', '0054_merge_20260513_2103'),
    ]

    operations = [
    ]
