# Generated by Django 6.0.3 on 2026-05-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0054_vehicle_year_of_manufacture'),
        ('vehicles', '0055_merge_20260520_1605'),
    ]

    operations = [
    ]
