# Generated by Django 6.0.3 on 2026-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0056_merge_20260520_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
