# Generated by Django 6.0.3 on 2026-05-22 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0057_alter_busgroup_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerevision',
            name='edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
