# Generated by Django 6.0.3 on 2026-05-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0058_vehiclerevision_edit_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_support_vehicle',
            field=models.BooleanField(default=False, help_text='Use for fleet support vehicles. This stays in sync with feature 9.'),
        ),
    ]
