# Generated by Django 6.0.3 on 2026-06-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0055_preservation_ownership'),
        ('vehicles', '0059_alter_vehicle_fleet_support_vehicle'),
    ]

    operations = [
    ]
