# Generated by Django 6.0.3 on 2026-06-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0061_vehicle_joined_left_fleet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallivery',
            name='history_user',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='vehicle_single_preservation_owner',
        ),
        migrations.DeleteModel(
            name='HistoricalLivery',
        ),
    ]
