# Generated by Django 6.0.3 on 2026-06-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0062_remove_historicallivery_history_user_and_more'),
        ('vehicles', 'add_livery_fleet_dates'),
    ]

    operations = [
    ]
