# Generated by Django 6.0.3 on 2026-07-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0063_alter_livery_remove_fields_and_add_type_svg'),
        ('vehicles', '0064_previous_operators'),
    ]

    operations = [
    ]
