# Generated by Django 6.0.3 on 2026-07-01 19:21

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0065_merge_20260701_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livery',
            name='svg',
            field=models.FileField(blank=True, help_text='SVG or PNG file with aspect ratio 3:2 (e.g., 90x60, 180x120)', null=True, upload_to='liveries/svg', validators=[vehicles.models.validate_livery_image_file]),
        ),
    ]
