# Generated by Django 6.0.3 on 2026-07-08 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0062_organisation_about'),
        ('bustimes', '0019_rename_bustimes_route_link_order_idx_bustimes_ro_route_l_ac4f76_idx_and_more'),
        ('vehicles', '0068_vehiclerevision_operated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('vehicle', 'to_operated_by'), name='unique_pending_operated_by'),
        ),
    ]
