# Generated by Django 6.0.3 on 2026-07-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0063_historical_vehicle'),
        ('vehicles', '0069_vehiclerevision_unique_pending_operated_by'),
    ]

    operations = [
    ]
