# Generated by Django 6.0.3 on 2026-07-20 21:44

import busstops.fields
import django.db.models.functions.text
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0063_governmentauthority_operator_government_authority'),
        ('bustimes', '0021_simulationconfig'),
        ('vehicles', '0070_merge_20260713_2149'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historicalvehicle',
            name='historical_fleet_code',
        ),
        migrations.RemoveIndex(
            model_name='historicalvehicle',
            name='historical_reg',
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=vehicles.models.vehicle_slug, unique=True),
        ),
        migrations.AddIndex(
            model_name='historicalvehicle',
            index=models.Index(django.db.models.functions.text.Upper('fleet_code'), name='historical_fleet_code'),
        ),
        migrations.AddIndex(
            model_name='historicalvehicle',
            index=models.Index(django.db.models.functions.text.Upper('reg'), name='historical_reg'),
        ),
    ]
