# Generated by Django 5.2 on 2026-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0071_remove_historicalvehicle_historical_fleet_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="advanced",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Advanced metadata for power users (historic owners, internal notes, etc.)",
                null=True,
            ),
        ),
    ]
