# Generated by Django 6.0.3 on 2026-07-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0050_advanced_field'),
        ('vehicles', '0097_vehicle_advanced'),
    ]

    operations = [
    ]
