# Generated by Django 6.0.3 on 2026-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0098_merge_0050_advanced_field_0097_vehicle_advanced"),
    ]

    operations = [
        # Add technical spec fields only if they don't already exist
        # Use conditional SQL to handle databases where columns may already exist
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Add capacity if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'vehicles_vehicle' 
                    AND column_name = 'capacity'
                ) THEN
                    ALTER TABLE vehicles_vehicle ADD COLUMN capacity INTEGER;
                ELSE
                    -- Make capacity nullable if it exists and is NOT NULL
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'vehicles_vehicle' 
                        AND column_name = 'capacity'
                        AND is_nullable = 'NO'
                    ) THEN
                        ALTER TABLE vehicles_vehicle ALTER COLUMN capacity DROP NOT NULL;
                    END IF;
                END IF;
                
                -- Add chassis if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'vehicles_vehicle' 
                    AND column_name = 'chassis'
                ) THEN
                    ALTER TABLE vehicles_vehicle ADD COLUMN chassis VARCHAR(50);
                END IF;
                
                -- Add emissions_rating if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'vehicles_vehicle' 
                    AND column_name = 'emissions_rating'
                ) THEN
                    ALTER TABLE vehicles_vehicle ADD COLUMN emissions_rating VARCHAR(32);
                END IF;
                
                -- Add gearbox if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'vehicles_vehicle' 
                    AND column_name = 'gearbox'
                ) THEN
                    ALTER TABLE vehicles_vehicle ADD COLUMN gearbox VARCHAR(50);
                END IF;
                
                -- Add length if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'vehicles_vehicle' 
                    AND column_name = 'length'
                ) THEN
                    ALTER TABLE vehicles_vehicle ADD COLUMN length VARCHAR(50);
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
