# Generated by Django 6.0.3 on 2026-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0098_merge_0050_advanced_field_0097_vehicle_advanced"),
    ]

    operations = [
        # Make the existing capacity column nullable to fix the NOT NULL constraint
        migrations.RunSQL(
            "ALTER TABLE vehicles_vehicle ALTER COLUMN capacity DROP NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        # Add the capacity field to the model (uses existing column)
        migrations.AddField(
            model_name="vehicle",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vehicle seating capacity (number of passengers)",
                null=True,
            ),
        ),
        # Add the remaining new fields (choices are loaded from JSON files, not hardcoded)
        migrations.AddField(
            model_name="vehicle",
            name="chassis",
            field=models.CharField(
                blank=True,
                help_text="Vehicle chassis type",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="emissions_rating",
            field=models.CharField(
                blank=True,
                help_text="Vehicle emissions rating",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="gearbox",
            field=models.CharField(
                blank=True,
                help_text="Vehicle gearbox/transmission type",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="length",
            field=models.CharField(
                blank=True,
                help_text="Vehicle length (e.g., '12m', '10.5m', '18m articulated')",
                max_length=50,
            ),
        ),
    ]
