# Generated by Django 6.0.3 on 2026-09-29

import vehicles.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0098_merge_0050_advanced_field_0097_vehicle_advanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livery',
            name='left_css',
            field=vehicles.fields.CSSField(blank=True, help_text='Automatically generated from colours and angle', max_length=8192, verbose_name='Left CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='right_css',
            field=vehicles.fields.CSSField(blank=True, help_text='Should be a mirror image of the left CSS', max_length=8192, verbose_name='Right CSS'),
        ),
    ]
