# Generated by Django 6.0.3 on 2026-09-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0063_governmentauthority_operator_government_authority'),
        ('vehicles', '0099_remove_busgroup_vehicles_and_add_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='operated_by',
            field=models.ForeignKey(blank=True, help_text='Loan operator (if this vehicle is on loan to a different operator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_vehicles', to='busstops.operator'),
        ),
    ]
