# Generated by Django 6.0.3 on 2026-09-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0100_add_length_advanced_field'),
        ('vehicles', '0102_merge_20260903_0018'),
    ]

    operations = [
    ]
