# Generated by Django 6.0.3 on 2026-09-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0102_fix_orphan_technical_columns'),
        ('vehicles', '0103_merge_20260905_1841'),
    ]

    operations = [
    ]
