# Generated by Django 6.0.3 on 2026-09-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0099_vehicle_technical_specs'),
        ('vehicles', '0103_drop_orphan_column_not_null'),
        ('vehicles', '0104_merge_20260907_2145'),
    ]

    operations = [
    ]
