# Generated by Django 6.0.3 on 2026-09-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0102_add_float_field_type'),
        ('vehicles', '0105_merge_20260908_2207'),
    ]

    operations = [
    ]
