# Generated by Django 6.0.3 on 2026-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0106_merge_20260918_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Vehicle seating capacity (number of passengers)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(blank=True, help_text='Vehicle chassis type', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emissions_rating',
            field=models.CharField(blank=True, help_text='Vehicle emissions rating', max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(blank=True, help_text='Vehicle gearbox/transmission type', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length',
            field=models.CharField(blank=True, help_text="Vehicle length (e.g., '12m', '10.5m', '18m articulated')", max_length=50),
        ),
    ]
