# Generated by Django 6.0.3 on 2026-09-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0099_vehiclerevision_permissions'),
        ('vehicles', '0107_vehicle_capacity_vehicle_chassis_and_more'),
    ]

    operations = [
    ]
