# Generated by Django 6.0.3 on 2026-09-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0104_vehicle_first_tracked_at'),
        ('vehicles', '0108_merge_20260919_2226'),
    ]

    operations = [
    ]
