# Generated by Django 6.0.3 on 2026-10-09 17:27

import django.db.models.deletion
from django.db import migrations, models


def convert_all_chassis_to_null(apps, schema_editor):
    """Convert all chassis values to NULL before altering to ForeignKey."""
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    Vehicle.objects.all().update(chassis=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0112_merge_20261009_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmissionsStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'emissions standard',
                'verbose_name_plural': 'emissions standards',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='emissions_rating',
        ),
        migrations.RunPython(convert_all_chassis_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.ForeignKey(blank=True, help_text='Vehicle chassis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.chassis'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emissions_standard',
            field=models.ForeignKey(blank=True, help_text='Vehicle emissions standard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.emissionsstandard'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.ForeignKey(blank=True, help_text='Vehicle engine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.engine'),
        ),
    ]
